[workspace]
resolver = "2"
members = ["core", "daemon", "client", "tui", "bevy"]
default-members = ["core", "daemon", "client", "tui"]
exclude = ["core/fuzz"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
postcard = { version = "1", features = ["use-std"] }
ed25519-dalek = { version = "3", features = ["rand_core"] }
data-encoding = "2"
